name: Test CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master
 
jobs:
  Handle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Run test
      id: unitTest
      run: mvn test
    - name: Upload test report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports/*.xml
    - name: Code Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: jacoco.xml
        directory: ./target/site/jacoco/
    - name: Notify pusher (Success)
      if: github.event_name == 'push'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_HOST }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: 'â­ [GITHUB BOT][SUCCESS] Push report'
        from: Github Action Bot
        to: ${{ secrets.SMTP_RECEIVER }}
        body: |
          Push created by ${{ github.event.pusher.name }} has been succeeded.
          Detail: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
    - name: Notify pusher (Failed, Other cases)
      if: failure() && github.event_name == 'push' && steps.unitTest.outputs.status != 'failure'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_HOST }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: 'ðŸ”¥ [GITHUB BOT][FAILED] Push report'
        from: Github Action Bot
        to: ${{ secrets.SMTP_RECEIVER }}
        body: |
          Push created by ${{ github.event.pusher.name }} has been failed.
          Reason: Something went wrong.
          Detail: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
  Reporter:
    needs: [handle]
    runs-on: ubuntu-latest
    if: always() && (needs.handle.result == 'failure')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download test report
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: artifact
      - name: Process report
        id: reportAction
        uses: dorny/test-reporter@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          name: Unit test result
          path: 'artifact/*.xml'
          reporter: java-junit
          fail-on-error: false
      - name: Get HTML result
        if: github.event_name == 'push'
        uses: actions/github-script@v6
        with:
          script: |
            const runInfo = await github.rest.actions.listJobsForWorkflowRun({
              run_id: context.runId,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            const testResult = runInfo.data.jobs.find(item => item.name === 'Unit test result')
            const htmlUrl = testResult.html_url
            core.exportVariable('htmlUrl', htmlUrl)
      - name: Notify pull request creator (Failed test)
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ${{ env.htmlUrl }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify pusher (Failed test)
        if: github.event_name == 'push'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'ðŸ”¥ [GITHUB BOT][FAILED] Push report (Unit test failed)'
          from: Github Action Bot
          to: ${{ secrets.SMTP_RECEIVER }}
          body: |
            Push created by ${{ github.event.pusher.name }} has been failed.
            Reason: Unit test failed.
            Detail: ${{ env.htmlUrl }}


