name: Unit Test & Coverage

on: [pull_request, push]
 
jobs:
  Check:
    runs-on: ubuntu-latest
    outputs:
      isMain: ${{ steps.main.outputs.valid }}
    env:
      isMain: ${{ github.ref_name == secrets.MAIN_BRANCH || github.event_name == 'pull_request' }}
    steps:
      - name: Dispatch
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              ref: context.ref,
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test-reporter-pr.yml',
              inputs: {
                something: false
              }
            })
            console.log(result)
      - name: Check
        id: main
        run: echo '::set-output name=valid::${{ env.isMain }}'
  Handle:
    needs: [Check]
    if: needs.Check.outputs.isMain == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Run test
      id: unitTest
      run: mvn test
    - name: Upload test report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports/*.xml
    - name: Code Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: jacoco.xml
        directory: ./target/site/jacoco/